Simple Polling Website/vote/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('votings/', include('votings.urls')),
    path('admin/', admin.site.urls),
]

Simple Polling Website/votings/urls.py
from django.urls import path
from . import views


app_name = 'votings'

urlpatterns = [
    # ex: /votgins/
    path('', views.index, name='index'),
    # ex: /votings/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /votings/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /votings/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

Simple Polling Website/votings/models.py

from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length = 200)
    pub_date = models.DateTimeField('Published date')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    choice_text = models.CharField(max_length = 200)
    votes = models.IntegerField(default = 0)

    def __str__(self):
        return self.choice_text
# Create your models here.

Simple Polling Website/votings/views.py

# Create your views here.
from django.http import HttpResponse,HttpResponseRedirect
from .models import Choice, Question
from django.shortcuts import get_object_or_404, render
from django.urls import reverse


def vote(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    try:
        selected_choice = question.choice_set.get(pk = request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'votings/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('votings:results', args=(question.id,)))


def index(request):
    question_list = Question.objects.all()
    context = {'question_list': question_list}
    return render(request, 'votings/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    return render(request, 'votings/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    return render(request, 'votings/results.html', {'question': question})

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)


Simple Polling Website/votings/templates/votings/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'votings:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

Simple Polling Website/votings/templates/votings/index.html


{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'votings/style.css' %}">

{% if question_list %}
    <ul>
    {% for question in question_list %}
        <li><a href="{% url 'votings:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

Simple Polling Website/votings/templates/votings/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for chioce in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'votings:detail' question.id %}">Vote again?</a>